# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'W:\Python\Project\Day7\testui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressQueryBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressQueryBar.setGeometry(QtCore.QRect(30, 630, 841, 23))
        self.progressQueryBar.setProperty("value", 0)
        self.progressQueryBar.setObjectName("progressQueryBar")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(30, 20, 841, 571))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.editPersonName = QtWidgets.QLineEdit(self.groupBox)
        self.editPersonName.setObjectName("editPersonName")
        self.gridLayout.addWidget(self.editPersonName, 1, 0, 1, 2)
        self.btnQueryPersonInfo = QtWidgets.QPushButton(self.groupBox)
        self.btnQueryPersonInfo.setObjectName("btnQueryPersonInfo")
        self.gridLayout.addWidget(self.btnQueryPersonInfo, 2, 0, 1, 2)
        self.tablePersonInfo = QtWidgets.QTableWidget(self.groupBox)
        self.tablePersonInfo.setObjectName("tablePersonInfo")
        self.tablePersonInfo.setColumnCount(0)
        self.tablePersonInfo.setRowCount(0)
        self.gridLayout.addWidget(self.tablePersonInfo, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(183, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.btnQueryMovieList = QtWidgets.QPushButton(self.groupBox)
        self.btnQueryMovieList.setObjectName("btnQueryMovieList")
        self.gridLayout.addWidget(self.btnQueryMovieList, 4, 1, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnGenRelativeGraph = QtWidgets.QPushButton(self.layoutWidget)
        self.btnGenRelativeGraph.setObjectName("btnGenRelativeGraph")
        self.gridLayout_2.addWidget(self.btnGenRelativeGraph, 3, 2, 1, 1)
        self.btnQueryMovieInfo = QtWidgets.QPushButton(self.layoutWidget)
        self.btnQueryMovieInfo.setObjectName("btnQueryMovieInfo")
        self.gridLayout_2.addWidget(self.btnQueryMovieInfo, 1, 2, 1, 1)
        self.tableMovieInfo = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableMovieInfo.setObjectName("tableMovieInfo")
        self.tableMovieInfo.setColumnCount(0)
        self.tableMovieInfo.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableMovieInfo, 2, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 2)
        self.tableMovieList = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableMovieList.setObjectName("tableMovieList")
        self.tableMovieList.setColumnCount(0)
        self.tableMovieList.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableMovieList, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnQueryPersonInfo.clicked.connect(self.tablePersonInfo.show) # type: ignore
        self.btnQueryMovieList.clicked.connect(self.tableMovieList.show) # type: ignore
        self.btnQueryMovieInfo.clicked.connect(self.tableMovieInfo.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "演员信息"))
        self.label.setText(_translate("MainWindow", "请输入演员名称"))
        self.btnQueryPersonInfo.setText(_translate("MainWindow", "查询演员信息"))
        self.btnQueryMovieList.setText(_translate("MainWindow", "查询电影列表"))
        self.btnGenRelativeGraph.setText(_translate("MainWindow", "生成关系图"))
        self.btnQueryMovieInfo.setText(_translate("MainWindow", "查询电影信息"))
